# Generated by Django 3.2.1 on 2021-06-09 23:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('cards', '0010_auto_20210610_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_level_cost', models.IntegerField(null=True,
                                                        validators=[django.core.validators.MinValueValidator(0),
                                                                    django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProposedCardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',
                 models.CharField(help_text="Displayed card's name. Must be unique.", max_length=50, unique=True)),
                ('tooltip',
                 models.TextField(help_text="Card's description. Gets displayed together with the card as a tooltip.")),
                ('image', models.ImageField(blank=True, help_text="An image. We don't reallyknow what should that be.",
                                            null=True, upload_to='proposed_content/cards/images/')),
                ('subject', models.CharField(
                    help_text='Subject name. In the future this field will be an id pointing to Subject object.',
                    max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProposedCardLevelEffects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(choices=[(1, 'Player'), (2, 'Opponent')], default=2)),
                ('power', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0),
                                                                     django.core.validators.MaxValueValidator(100)])),
                ('range', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0),
                                                                   django.core.validators.MaxValueValidator(100)])),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects',
                                           to='proposed_content.proposedcard')),
                ('card_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardeffect')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='proposedcard',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels',
                                    to='proposed_content.proposedcardinfo'),
        ),
        migrations.AddField(
            model_name='proposedcard',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardlevel'),
        ),
        migrations.AddConstraint(
            model_name='proposedcard',
            constraint=models.UniqueConstraint(fields=('info', 'level'), name='unique_ProposedCardInfo_level'),
        ),
    ]
