# Generated by Django 3.2.4 on 2021-06-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('proposed_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedcardinfo',
            name='name',
            field=models.CharField(help_text="Displayed card's name.", max_length=50),
        ),
    ]
