# Generated by Django 3.2.1 on 2021-08-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposed_content', '0002_alter_proposedcardinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedcardinfo',
            name='comment',
            field=models.TextField(blank=True, help_text='Comment field for users to send a message to the admins alongside their created card', max_length=150, null=True),
        ),
    ]
