# Generated by Django 3.2.1 on 2021-10-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposed_content', '0003_proposedcardinfo_comment'),
        ('proposed_content', '0004_alter_proposedcard_effects_description'),
    ]

    operations = [
    ]
