# Generated by Django 3.2 on 2021-07-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposed_content', '0003_auto_20210725_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedcard',
            name='effects_description',
            field=models.CharField(default='description', help_text="A brief description of this level's effects.", max_length=100, null=True),
        ),
    ]
