# Generated by Django 3.2.4 on 2021-10-12 17:01

import cards.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposed_content', '0006_auto_20211011_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedcardinfo',
            name='image',
            field=models.FileField(blank=True, help_text="An image. We don't reallyknow what should that be.", null=True, upload_to='cards.ImageStorage/bytes/filename/mimetype', validators=[cards.validators.validate_file_size]),
        ),
    ]
