# Generated by Django 3.2.4 on 2021-10-21 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposed_content', '0007_alter_proposedcardinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedcardinfo',
            name='owner',
            field=models.ForeignKey(help_text='A reference to Django user model', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
