# Generated by Django 3.2.4 on 2021-11-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposed_content', '0008_proposedcardinfo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedcard',
            name='effects_description',
            field=models.CharField(default='description', help_text="A brief description of this level's effects.", max_length=500, null=True),
        ),
    ]
