# Generated by Django 3.2 on 2021-04-29 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('IngameUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('displayedUsername', models.CharField(max_length=50)),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IngameUsers.semester')),
            ],
        ),
        migrations.DeleteModel(
            name='BasicUserInfo',
        ),
    ]
