# Generated by Django 3.2 on 2021-05-14 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cards', '0004_auto_20210507_1008'),
        ('IngameUsers', '0002_auto_20210429_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_number', models.PositiveIntegerField()),
                ('deck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='IngameUsers.deck')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck',
                                                   to='IngameUsers.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile',
                                           to='cards.card')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards',
                                                   to='IngameUsers.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='card1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_card1',
                                    to='IngameUsers.usercard'),
        ),
        migrations.AddField(
            model_name='deck',
            name='card2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_card2',
                                    to='IngameUsers.usercard'),
        ),
        migrations.AddField(
            model_name='deck',
            name='card3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_card3',
                                    to='IngameUsers.usercard'),
        ),
        migrations.AddField(
            model_name='deck',
            name='card4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_card4',
                                    to='IngameUsers.usercard'),
        ),
        migrations.AddField(
            model_name='deck',
            name='card5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_card5',
                                    to='IngameUsers.usercard'),
        ),
        migrations.AddConstraint(
            model_name='userdeck',
            constraint=models.UniqueConstraint(fields=('deck_number', 'deck', 'user_profile'),
                                               name='user_deck_composite_pk'),
        ),
        migrations.AddConstraint(
            model_name='usercard',
            constraint=models.UniqueConstraint(fields=('user_profile', 'card'), name='user_card_composite_pk'),
        ),
    ]
