# Generated by Django 3.2.1 on 2021-06-09 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IngameUsers', '0003_auto_20210514_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='displayedUsername',
            field=models.CharField(help_text='Pretty username available to anyone', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='semester',
            field=models.ForeignKey(help_text='Semester number.', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='IngameUsers.semester'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='A reference to Django user model',
                                       on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
