# Generated by Django 3.2.4 on 2021-10-18 20:21

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('IngameUsers', '0004_auto_20210609_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': [django.db.models.functions.text.Upper('displayedUsername')]},
        ),
    ]
