# Generated by Django 3.2.5 on 2021-11-30 13:19

import cards.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IngameUsers', '0005_alter_userprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.BinaryField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, help_text='# Player profile image', null=True, upload_to='IngameUsers.ImageStorage/bytes/filename/mimetype', validators=[cards.validators.validate_file_size]),
        ),
    ]
