# Generated by Django 3.2.5 on 2021-12-15 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IngameUsers', '0006_auto_20211130_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.PositiveIntegerField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_exp', to='IngameUsers.userprofile')),
            ],
        ),
    ]
