# Generated by Django 3.2.5 on 2021-12-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IngameUsers', '0007_userexp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExp',
            new_name='UserStats',
        ),
    ]
