# Generated by Django 3.2.5 on 2021-12-15 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IngameUsers', '0008_rename_userexp_userstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='IngameUsers.userprofile'),
        ),
    ]
