# Generated by Django 3.2.10 on 2022-01-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('IngameUsers', '0009_alter_userstats_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='skill_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
