# Generated by Django 3.2.10 on 2022-01-15 19:48

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('IngameUsers', '0012_add_skillpoints_to_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-user_stats__exp', django.db.models.functions.text.Upper('displayedUsername')]},
        ),
    ]
