# Generated by Django 3.2 on 2021-05-04 12:44

from django.db import migrations, models
from ..models import CardLevel


def insert_all_values_to_db(apps, schema_editor):
    """
    Inserts all possible CardLevel records to database.
    """

    CardLevel.objects.all().delete()
    for value in CardLevel.Level.values:
        cLvl = CardLevel.objects.create(level=value)
        cLvl.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardLevel',
            fields=[
                ('level', models.IntegerField(choices=[(1, 'Common')], default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RunPython(insert_all_values_to_db)
    ]
