# Generated by Django 3.2 on 2021-05-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardEffect',
            fields=[
                ('id', models.IntegerField(choices=[(1, 'Zadawanie obrażeń'), (2, 'Tarcza'), (3, 'Losowa zamiana kolejności kart'), (4, 'Zatrzymanie na jedną turę'), (5, 'Dwukrotne wykonanie się karty'), (6, 'Leczenie'), (7, 'Blokowanie następnej karty'), (8, 'Zwiększenie mocy następnej karty'), (9, 'Pomijanie następnej karty')], default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('tooltip', models.TextField(max_length=150, null=True)),
            ],
        ),
        migrations.RunSQL(
            r"INSERT INTO cards_cardeffect (id, name) VALUES (1, 'Zadawanie obrażeń'), (2, 'Tarcza'), (3, 'Losowa zamiana kolejności kart'), (4, 'Zatrzymanie na jedną turę'), (5, 'Dwukrotne wykonanie się karty'), (6, 'Leczenie'), (7, 'Blokowanie następnej karty'), (8, 'Zwiększenie mocy następnej karty'), (9, 'Pomijanie następnej karty');")
    ]
