# Generated by Django 3.2 on 2021-05-05 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tooltip', models.TextField()),
                ('image', models.ImageField(null=True, blank=True, upload_to='cards/images/')),
                ('subject', models.CharField(max_length=50, null=True))
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_level_cost', models.IntegerField()),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardinfo')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardlevel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('info', 'level'), name='unique_info_level'),
        ),
    ]
