# Generated by Django 3.2 on 2021-05-06 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20210505_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLevelEffects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(choices=[(1, 'Player'), (2, 'Opponent')], default=2)),

                ('power', models.IntegerField(null=True)),
                ('range', models.FloatField(null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='cards.card')),
                ('card_effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardeffect')),
            ],
        ),
    ]
