# Generated by Django 3.2 on 2021-05-05 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_cardinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardlevel'),
        ),
    ]
