# Generated by Django 3.2 on 2021-05-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20210507_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardeffect',
            name='has_modifier',
            field=models.BooleanField(default=False),
        ),
    ]
