# Generated by Django 3.2 on 2021-05-24 17:47

from django.db import migrations, models

from cards.models import CardEffect, CardLevel


def insert_card_effects_values_to_db(apps, schema_editor):
    CardEffect.objects.all().delete()
    for value in CardEffect.EffectId.values:
        item = CardEffect.objects.create(id=value)
        item.save()


def insert_card_levels_values_to_db(apps, schema_editor):
    """
    Inserts all possible CardLevel records to database.
    """

    CardLevel.objects.all().delete()
    for value in CardLevel.Level.values:
        cLvl = CardLevel.objects.create(level=value)
        cLvl.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20210507_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardeffect',
            name='has_modifier',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(insert_card_levels_values_to_db),
        migrations.RunPython(insert_card_effects_values_to_db)
    ]
