# Generated by Django 3.2 on 2021-05-30 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_cardeffect_has_modifier'),
        ('cards', '0006_alter_cardeffect_id'),
    ]

    operations = [
    ]
