# Generated by Django 3.2 on 2021-05-30 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_cardeffect_id'),
        ('cards', '0006_cardeffect_has_modifier'),
    ]

    operations = [
    ]
