# Generated by Django 3.2 on 2021-05-30 21:10

from django.db import migrations

from cards.models import CardEffect, CardLevel


def insert_card_effects_values_to_db(apps, schema_editor):
    for value in CardEffect.EffectId.values:
        if not CardEffect.objects.filter(pk=value).exists():
            item = CardEffect.objects.create(id=value)
            item.save()

    # Modifying has_modifier values for some effects
    # One may also use views to modify them, we just set them here initially.
    def change_modifier_true(effect: CardEffect.EffectId):
        effect = CardEffect.objects.get(pk=effect.value)
        effect.has_modifier = True
        effect.save()

    change_modifier_true(CardEffect.EffectId.DMG)
    change_modifier_true(CardEffect.EffectId.SHIELD)
    change_modifier_true(CardEffect.EffectId.HEAL)


class Migration(migrations.Migration):
    dependencies = [
        ('cards', '0007_merge_20210530_2310')
    ]

    operations = [
        migrations.RunPython(insert_card_effects_values_to_db)
    ]
