# Generated by Django 3.2.1 on 2021-06-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cards', '0009_auto_20210609_2359'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='card',
            name='unique_info_level',
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('info', 'level'), name='unique_CardInfo_level'),
        ),
    ]
