# Generated by Django 3.2.4 on 2021-06-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cards', '0010_auto_20210610_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='name',
            field=models.CharField(help_text="Displayed card's name.", max_length=50),
        ),
        migrations.AddConstraint(
            model_name='cardinfo',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_CardInfo_name'),
        ),
    ]
