# Generated by Django 3.2.4 on 2021-10-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20210613_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='image',
            field=models.FileField(blank=True, help_text="An image. We don't reallyknow what should that be.", null=True, upload_to='cards/images/'),
        ),
    ]
