# Generated by Django 3.2 on 2021-07-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20210613_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='effects_description',
            field=models.CharField(default='description', help_text="A brief description of this level's effects.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardleveleffects',
            name='target',
            field=models.IntegerField(choices=[(1, 'gracz'), (2, 'przeciwnik')], default=2),
        ),
    ]
