# Generated by Django 3.2.5 on 2021-10-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_auto_20210725_1652'),
        ('cards', '0013_alter_cardinfo_image'),
    ]

    operations = [
    ]
