# Generated by Django 3.2.4 on 2021-10-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_merge_20211009_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardeffect',
            name='tooltip',
            field=models.TextField(help_text='Effect description', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='name',
            field=models.CharField(help_text="Displayed card's name.", max_length=36),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='subject',
            field=models.CharField(help_text='Subject name. In the future this field will be an id pointing to Subject object.', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='tooltip',
            field=models.TextField(help_text="Card's description. Gets displayed together with the card as a tooltip.", max_length=80),
        ),
        migrations.AlterField(
            model_name='cardlevel',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
