# Generated by Django 3.2.4 on 2021-10-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_auto_20211011_1708'),
        ('cards', '0015_fill_missing_modifiers'),
    ]

    operations = [
    ]
