# Generated by Django 3.2.4 on 2021-10-12 17:01

import cards.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_merge_20211011_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.BinaryField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='image',
            field=models.FileField(blank=True, help_text="An image. We don't reallyknow what should that be.", null=True, upload_to='cards.ImageStorage/bytes/filename/mimetype', validators=[cards.validators.validate_file_size]),
        ),
    ]
