# Generated by Django 3.2.4 on 2021-11-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0018_alter_card_effects_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardeffect',
            name='icon',
            field=models.FileField(blank=True, help_text='# Holds an image representing the effect', null=True, upload_to='cards.ImageStorage/bytes/filename/mimetype'),
        ),
    ]
