### Installs dependencies
FROM node:16-alpine3.12 as builder

# From build arg
ARG API_URL="localhost:8000"
ENV API_URL=${API_URL}

WORKDIR /frontend
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@4.0.3 -g --silent


COPY . ./
RUN npm run build


FROM nginx:stable-alpine

WORKDIR /frontend
COPY --from=builder /frontend/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
