version: '3.2'

services:
  wmiadventure-backend:
    image: wmiadventure.azurecr.io/wmiadventure:v1
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/WMIAdventure_backend:/backend/
    ports:
      - 8000:8000

  wmiadventure-frontend:
    image: wmiadventure.azurecr.io/frontend:v1
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal -d
      wmiadventure.westeurope.cloudapp.azure.com --email komar86311@gmail.com
      --agree-tos
