name: Test Pull Requests

on: 
  pull_request_target:
    branches: '**'
  push:
    branches:
      - '**'
      - '!main'

jobs:
  test-django:
    runs-on: ubuntu-latest
    name: Tests for Django backend app
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./WMIAdventure/backend/requirements.txt
    - name: Run Django tests
      run: |
        python ./WMIAdventure/backend/WMIAdventure_backend/manage.py test ./WMIAdventure/backend/WMIAdventure_backend/

  test-frontend:
  
    runs-on: ubuntu-latest
    name: Tests for React frontend app
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: WMIAdventure/frontend/package-lock.json
    - name: Install JS dependencies
      run: |
        cd ./WMIAdventure/frontend
        npm install 
    - name: Test
      run: |
        cd ./WMIAdventure/frontend
        npm run test -- --passWithNoTests
